---
- name: Install dependencies
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - p7zip-full
    - xorriso
    - gpg
    - curl
  when: ansible_os_family != "Darwin"

- name: Install dependencies (macOS)
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - p7zip
    - xorriso
    - gnupg
    - curl
  when: ansible_os_family == "Darwin"

- name: Launch dirmngr if it isn't running
  shell:
    cmd: "ps aux | grep [d]irmngr || dirmngr"

- name: Create the temporary directory
  file:
    path: "{{ target_dir }}"
    state: directory
